sudo: required
services:
  - docker

before_install:
  - docker build -t rstkhldntsk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rstkhldntsk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-307196522452"
  on:
    branch: main
