sudo: required
services:
  - docker
before_install:
  - docker build -t rstkhldntsk/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rstkhldntsk/complex-test  npm test

after_success:
  - docker build -t rstkhldntsk/client ./client
  - docker build -t rstkhldntsk/nginx ./nginx
  - docker build -t rstkhldntsk/server ./server
  - docker build -t rstkhldntsk/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rstkhldntsk/client
  - docker push rstkhldntsk/nginx
  - docker push rstkhldntsk/server
  - docker push rstkhldntsk/worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: Docker-multi
  env: Dockermulti-env
  bucket_name: elasticbeanstalk-eu-central-1-307196522452
  bucket_path: multi-docker
  on:
    branch: main
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
