version: "3"
services:
  client:
    image: "rstkhldntsk/client"
    hostname: client
  server:
    image: "rstkhldntsk/server"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "rstkhldntsk/worker"
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "rstkhldntsk/nginx"
    hostname: nginx
    ports:
      - "80:80"
